build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true

naming:
  active: true
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'

style:
  active: true

comments:
  active: false
