/* Generated by tools/generate_icons.py. Do not edit. */
#pragma once
#include <stdint.h>

typedef enum {
    ICON_GENERIC,
    ICON_MICROPHONE,
    ICON_RECORDING,
    ICON_SESSION,
    ICON_QUESTION,
    ICON_WARNING,
    ICON_TASK,
    ICON_LIST,
    ICON_NOTE,
    ICON_FACT,
    ICON_DECISION,
    ICON_TOPIC,
    ICON_CHAT,
    ICON_INFO,
    ICON_SEV_INFO,
    ICON_SEV_SUCCESS,
    ICON_SEV_WARNING,
    ICON_SEV_ERROR,
    ICON_SEV_CRITICAL,
    ICON_WIFI,
    ICON_WIFI_OFF,
    ICON_BATTERY,
    ICON_STORAGE,
    ICON_QUEUE,
    ICON_OFFLINE,
    ICON_MENU,
    ICON_HOME,
    ICON_HISTORY,
    ICON_COUNT
} icon_id;

typedef struct { uint16_t offset; uint8_t size; } icon_entry;
static const icon_entry icon_entries[ICON_COUNT] = {
    {0, 24}, /* generic */
    {72, 24}, /* microphone */
    {144, 24}, /* recording */
    {216, 24}, /* session */
    {288, 24}, /* question */
    {360, 24}, /* warning */
    {432, 24}, /* task */
    {504, 24}, /* list */
    {576, 24}, /* note */
    {648, 24}, /* fact */
    {720, 24}, /* decision */
    {792, 24}, /* topic */
    {864, 24}, /* chat */
    {936, 24}, /* info */
    {1008, 16}, /* sev_info */
    {1040, 16}, /* sev_success */
    {1072, 16}, /* sev_warning */
    {1104, 16}, /* sev_error */
    {1136, 16}, /* sev_critical */
    {1168, 24}, /* wifi */
    {1240, 24}, /* wifi_off */
    {1312, 28}, /* battery */
    {1424, 20}, /* storage */
    {1484, 20}, /* queue */
    {1544, 20}, /* offline */
    {1604, 24}, /* menu */
    {1676, 24}, /* home */
    {1748, 24}, /* history */
};
