#pragma once
// Monochrome symbols and the urgency fill patterns of the card side strip.
//
// The atlas is generated by tools/generate_icons.py and embedded; nothing here
// parses an image at runtime. Coordinates are logical, like text.h: x across
// the 480 px width, y down the 800 px height.
#include <stdbool.h>
#include "icon_data.h"

/* Fill patterns for the side strip. They carry urgency and get monotonically
 * darker, so a warning can never look lighter than something harmless. The
 * mapping from `color_role` to a step is in docs/DASHBOARD_UI.md. */
typedef enum {
    STRIP_PLAIN,   /* white with a hairline edge: muted, success, offline */
    STRIP_LIGHT,   /* 25 percent: neutral, info, secondary */
    STRIP_MEDIUM,  /* 50 percent: primary, recording */
    STRIP_HATCH,   /* diagonal: warning */
    STRIP_SOLID,   /* black: danger */
} strip_pattern;

/* Size in pixels of one icon; icons are square. */
int icon_size(icon_id id);

/* Draw an icon with its top-left corner at (x, y). With `knockout` the ink is
 * cleared instead of set, which is what a solid strip or a focused, inverted
 * card needs. */
void icon_draw(unsigned char *canvas, icon_id id, int x, int y, bool knockout);

/* Fill a rectangle with a strip pattern. The pattern is anchored to the canvas
 * origin, not to the rectangle, so adjacent fills line up. */
void icon_fill(unsigned char *canvas, int x, int y, int width, int height,
               strip_pattern pattern);

/* Whether the pattern puts ink on this canvas pixel. Use it when filling a
 * clipped shape pixel by pixel: icon_fill draws STRIP_PLAIN's hairline at the
 * right edge of whatever rectangle it is given, so a one pixel wide call would
 * turn every pixel into that edge. */
bool icon_pattern_ink(strip_pattern pattern, int x, int y);

/* Whether ink drawn directly on this pattern should be knocked out instead.
 * From the 50 percent step upwards a white mark separates from the ground more
 * strongly than a black one; below it, the opposite holds. Use this for marks
 * too small for a plate, where a white patch would read as a blob. Art symbols
 * do not need it: they sit on a plate and stay black on white throughout. */
bool icon_knockout_on(strip_pattern pattern);

/* Clear a rectangle to white, without the hairline that STRIP_PLAIN draws. */
void icon_plate(unsigned char *canvas, int x, int y, int width, int height);

/* Draw an icon on a cleared plate. This is how art symbols appear in the side
 * strip: the plate makes the symbol read identically on every urgency step,
 * which keeps the two meanings apart -- the strip carries urgency, the symbol
 * carries kind. Ink on the raster alone is unreadable from step 3 upwards, and
 * knocking the symbol out is unreadable on the light steps. */
void icon_draw_badge(unsigned char *canvas, icon_id id, int x, int y);

/* Invert a rectangle. Used for the focus marker. */
void icon_invert(unsigned char *canvas, int x, int y, int width, int height);

/* Ink only the border ring, `thickness` pixels wide, leaving the interior
 * untouched. Used for a persistent "this one is active" mark distinct from
 * the filled focus marker `icon_invert` draws, so a moving keyboard cursor
 * and a standing state indicator never look like the same thing. */
void icon_outline(unsigned char *canvas, int x, int y, int width, int height,
                  int thickness);
